deploymentConfig:
  org: baldummy
  repository: config-repo
  applicationName: testapplication
previewConfig:
  route:
    host:
      template: client-libraries-{SHA256_8CHAR_BRANCH_HASH}.shapp-test.os1.balgroupit.com
  replace:
  - path: testapplication.image.tag
    variable: GIT_COMMIT
  - path: testapplication.network.http.ingress.host
    variable: ROUTE_HOST
